const images = {
    logo: require('./Logo alta.png'),
    group: require('./Group 341.png'),
    frame: require('./Frame.png'),
    camera: require('./camera.svg'),
    monitor: require('./monitor.svg'),
    stateActive: require('./stateActive.svg'),
    stateStop: require('./stateStop.svg'),
    vector: require('./vector.svg'),
    search: require('./search.svg'),
    calender: require('./calendar.svg'),
    grow: require('./grow.svg'),
    stopAction: require('./stop-action.svg'),
    action: require('./action.svg'),
    nav_dashboard: require('./nav_dashboard.svg'),
    nav_monitor: require('./nav_monitor.svg'),
    nav_service: require('./nav_service.svg'),
    menu_number: require('./menu_number.svg'),
    nav_report: require('./nav_report.svg'),
    nav_setting: require('./nav_setting.svg'),
    add: require('./add.svg'),
    deviceUpdata: require('./deviceUpdata.svg'),
    arrow_right: require('./arrow_right.svg'),
    comeBack: require('./comeBack.svg'),
    cancel: require('./cancel.svg'),
    download: require('./download.svg'),
    logout: require('./logout.svg'),
    setting: require('./setting.svg'),
    waiting: require('./waiting.svg'),
    skip: require('./skip.svg'),
    used: require('./used.svg'),
    STT : require('./stt.svg'),
    userCall: require('./userCall.svg'),
    numberSkip: require('./numberSkip.svg'),
    down: require('./down.svg'),
    nav_dashboardActive: require('./nav_dasboardActive.svg'),
    monitorActive: require('./monitorActive.svg'),
    serviceActive: require('./serviceActive.svg'),
    numberActive: require('./numberActive.svg'),
    reportActive: require('./reportActive.svg'),
    settingActive: require('./settingActive.svg'),
    overService: require('./overService.svg'),
    overNumber: require('./overNumber.svg'),
    stateServiceActive: require('./stateServiceActive.svg'),
    stateNumberActive: require('./stateNumberActive.svg'),
    stateSkipActive: require('./stateSkipActive.svg')


};

export default images
